# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecWinUpd.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(40, 590, 211, 121))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Back.setFont(font)
        self.Back.setObjectName("Back")
        self.AddTeam = QtWidgets.QPushButton(self.centralwidget)
        self.AddTeam.setGeometry(QtCore.QRect(40, 100, 301, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.AddTeam.setFont(font)
        self.AddTeam.setObjectName("AddTeam")
        self.EditTeam = QtWidgets.QPushButton(self.centralwidget)
        self.EditTeam.setGeometry(QtCore.QRect(40, 230, 341, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.EditTeam.setFont(font)
        self.EditTeam.setObjectName("EditTeam")
        self.DeleteTeam = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteTeam.setGeometry(QtCore.QRect(40, 360, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.DeleteTeam.setFont(font)
        self.DeleteTeam.setObjectName("DeleteTeam")
        self.Commands = QtWidgets.QPushButton(self.centralwidget)
        self.Commands.setGeometry(QtCore.QRect(640, 100, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Commands.setFont(font)
        self.Commands.setObjectName("Commands")
        self.Players = QtWidgets.QPushButton(self.centralwidget)
        self.Players.setGeometry(QtCore.QRect(640, 360, 411, 91))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Players.setFont(font)
        self.Players.setObjectName("Players")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Back.setText(_translate("MainWindow", "Назад"))
        self.AddTeam.setText(_translate("MainWindow", "Добавить команду"))
        self.EditTeam.setText(_translate("MainWindow", "Редактировать команду"))
        self.DeleteTeam.setText(_translate("MainWindow", "Удалить команду"))
        self.Commands.setText(_translate("MainWindow", "Вывести список команд"))
        self.Players.setText(_translate("MainWindow", "Вывести список участников"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
